import { StyleSheet } from "react-native";

const TODO_HEIGHT = 166;
const BORDER_RADIUS = 24;

export const getTodoStyles = (theme) =>
  StyleSheet.create({
    numberContainer: {
      flexDirection: "column",
      width: "100%",
      height: TODO_HEIGHT,
      justifyContent: "center",
      alignItems: "center",
      gap: 20,
      borderRadius: 16,
      backgroundColor: "rgba(255, 255, 255, 0.2)",
      padding: 15,
      overflow: "hidden",
    },
    numberText: {
      color: "white",
      fontSize: 70,
      fontWeight: "bold",
    },
    finedContainer: {
      flexDirection: "column",
      width: "100%",
      height: TODO_HEIGHT,
      justifyContent: "center",
      alignItems: "center",
      gap: 20,
      borderRadius: 16,
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      padding: 15,
    },
    oneContainer: {
      flexDirection: "column",
      width: "100%",
      height: TODO_HEIGHT,
      justifyContent: "center",
      alignItems: "center",
      gap: 28,
      borderRadius: 16,
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      padding: 15,
    },
    infoContainer: {
      flexDirection: "row",
      width: 352,
      height: 166,
      borderRadius: BORDER_RADIUS,
      overflow: "hidden",
    },

    // Left styles (scroll down more for right styles)
    leftContainer: {
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      height: "100%",

      flex: 8,
      display: "flex",
      padding: 16,
      flexDirection: "column",
      justifyContent: "flex-end",
      alignItems: "flex-start",
      gap: 6,
      // borderWidth: 1,
      // borderColor: "white",
    },

    tagTitleContainer: {
      display: "flex",
      flexDirection: "column",
      justifyContent: "flex-end",
      alignItems: "flex-start",
      gap: 3,
      alignSelf: "stretch",
      // borderWidth: 1,
      // borderColor: "white",
      width: "100%",
    },
    tagContainer: {
      justifyContent: "center",
      alignItems: "center",
      backgroundColor:
        "linear-gradient(0deg, rgba(255, 255, 255, 0.07), rgba(255, 255, 255, 0.07)), rgba(255, 255, 255, 0.07)",
      borderRadius: 8,
      // paddingVertical: 8,
      paddingHorizontal: 10,
      height: 24,
      // borderWidth: 1,
      // borderColor: "white",
    },
    tagText: { 
      color: "white",
      fontSize: 12,
      lineHeight: 12,
      fontWeight: 500,
    },
    titleContainer: {
      height: 66,
      width: "100%",
      justifyContent: "center",
      // borderWidth: 1,
      // borderColor: "white",
    },
    titleText: {
      color: "white",
      fontSize: 40,
      fontWeight: "700",
    },
    amountContainer: {
      justifyContent: "center",
      alignItems: "center",
      backgroundColor:
        "linear-gradient(0deg, rgba(255, 255, 255, 0.07), rgba(255, 255, 255, 0.07)), rgba(255, 255, 255, 0.07)",
      borderRadius: 8,
      paddingHorizontal: 15,
      // paddingVertical: 10.5,
      maxWidth: 80,
      height: 35,
      // borderWidth: 1,
      // borderColor: "white",
    },
    amountText: {
      color: "white",
      fontSize: 20,
      lineHeight: 19,
      fontWeight: "bold",
    },

    // Right styles
    rightContainer: {
      borderTopRightRadius: 16,
      borderBottomRightRadius: 16,
      backgroundColor: "rgba(255, 255, 255, 0.2)",
      flex: 2,
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    rightDisabledContainer: {
      borderTopRightRadius: 16,
      borderBottomRightRadius: 16,
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      flex: 2,
      // width: "20%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
      borderLeftWidth: 1.5,
      borderLeftColor: "rgba(255, 255, 255, 0.1)",
    },
    checkDisabledContainer: {
      borderTopRightRadius: 16,
      borderBottomRightRadius: 16,
      backgroundColor: "rgba(255, 255, 255, 0.1)",
      flex: 2,
      // width: "20%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    disabledOpacity: {
      opacity: 0.6,
    },
    disabledCompleteContainer: {
      borderTopRightRadius: 16,
      borderBottomRightRadius: 16,
      backgroundColor: "rgba(255, 255, 255, 0.2)",
      flex: 2,
      // width: "20%",
      height: "100%",
      justifyContent: "center",
      alignItems: "center",
      overflow: "hidden",
    },
    upperHalfContainer: {
      flex: 4,
    },
    lowerHalfContainer: {
      flex: 5,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    tagDescriptionContainer: {
      flex: 1,
      flexDirection: "column",
      gap: 4,
      justifyContent: "flex-start",
    },
    todoNumber: {
      color: "white",
      fontSize: 30,
      fontWeight: "bold",
    },
    descriptionContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 4,
    },
    todoDescription: {
      color: "white",
      maxWidth: "80%",
      fontWeight: "500",
    },

    finedText: {
      color: theme.textDisabled,
      fontSize: 22,
      fontWeight: "bold",
    },

    infoText: {
      color: "white",
      opacity: 1,
      fontSize: 20,
      fontWeight: "bold",
      lineHeight: 20,
      // borderColor: "black",
      // borderWidth: 1,
    },

    todoButton: {
      flexDirection: "row",
      gap: 10,
      backgroundColor: "rgba(0, 0, 0, 0.2)",
      paddingHorizontal: 20,
      paddingVertical: 10,
      alignItems: "center",
      borderRadius: 10,
      // borderWidth: 1,
      // borderColor: "black",
    },

    todoButtonText: {
      color: "white",
      fontWeight: "bold",
      fontSize: 20,
      // borderWidth: 1,
      // borderColor: "black",
    },
  });
